languages = {
    "en": [
    "Predict how long it will take you to reach your social media followers goal", 
    "Initial followers",
    "Current followers",
    "Desired followers",
    "Time",
    "Oops! You forgot to fill in one or more fields.",
    "You can't use a number less than or equal to 0.",
    "The initial followers cannot be equal to or fewer than the current followers.",
    "The desired followers cannot be less than or equal to the initial followers or the current followers.",
    "You will reach your goal in:",
    "Predict",
    "Seconds",
    "Minutes",
    "Hours",
    "Days",
    ],
    
    "es": [
        "Predice cuánto tiempo te tomará alcanzar tu objetivo de seguidores en redes sociales",
"Seguidores iniciales",
"Seguidores actuales",
"Seguidores deseados",
"Tiempo",
"¡Ups! Olvidaste completar uno o más campos.",
"No puedes usar un número menor o igual a 0.",
"Los seguidores iniciales no pueden ser iguales o menores que los seguidores actuales.",
"Los seguidores deseados no pueden ser menores o iguales a los seguidores iniciales o los seguidores actuales.",
"Alcanzarás tu objetivo en:",
"Predecir",
"Segundos",
"Minutos",
"Horas",
"Días",
    ],
    
    "fr": [
    "Prévoyez combien de temps il vous faudra pour atteindre votre objectif de followers sur les réseaux sociaux",
    "Followers initiaux",
    "Followers actuels",
    "Followers désirés",
    "Temps",
    "Oups! Vous avez oublié de remplir un ou plusieurs champs.",
    "Vous ne pouvez pas utiliser un nombre inférieur ou égal à 0.",
    "Les followers initiaux ne peuvent pas être égaux ou inférieurs aux followers actuels.",
    "Les followers désirés ne peuvent pas être inférieurs ou égaux aux followers initiaux ou actuels.",
    "Vous atteindrez votre objectif en :",
    "Prédire",
    "Secondes",
    "Minutes",
    "Heures",
    "Jours",
],

"it": [
    "Prevedi quanto tempo ti ci vorrà per raggiungere il tuo obiettivo di follower sui social media",
    "Follower iniziali",
    "Follower attuali",
    "Follower desiderati",
    "Tempo",
    "Ops! Hai dimenticato di compilare uno o più campi.",
    "Non puoi usare un numero minore o uguale a 0.",
    "I follower iniziali non possono essere uguali o inferiori ai follower attuali.",
    "I follower desiderati non possono essere inferiori o uguali ai follower iniziali o ai follower attuali.",
    "Raggiungerai il tuo obiettivo in:",
    "Prevedi",
    "Secondi",
    "Minuti",
    "Ore",
    "Giorni",
],

"ar": [
    "تنبؤ بالمدة التي ستستغرقها للوصول إلى هدفك من متابعي وسائل التواصل الاجتماعي",
    "المتابعين الأولين",
    "المتابعين الحاليين",
    "المتابعين المرغوبين",
    "الوقت",
    "عذرا! لقد نسيت ملء أحد الحقول أو أكثر.",
    "لا يمكنك استخدام رقم أقل من أو يساوي 0.",
    "المتابعون الأوليون لا يمكن أن يكونوا متساوين أو أقل من المتابعين الحاليين.",
    "لا يمكن أن يكون المتابعون المطلوبون أقل من أو يساوون المتابعين الأوليين أو المتابعين الحاليين.",
    "ستصل إلى هدفك في:",
    "تنبؤ",
    "ثواني",
    "دقائق",
    "ساعات",
    "أيام",
],

"pt": [
    "Preveja quanto tempo levará para atingir sua meta de seguidores nas redes sociais",
    "Seguidores iniciais",
    "Seguidores atuais",
    "Seguidores desejados",
    "Tempo",
    "Oops! Você esqueceu de preencher um ou mais campos.",
    "Você não pode usar um número menor ou igual a 0.",
    "Os seguidores iniciais não podem ser iguais ou inferiores aos seguidores atuais.",
    "Os seguidores desejados não podem ser menores ou iguais aos seguidores iniciais ou aos seguidores atuais.",
    "Você alcançará sua meta em:",
    "Prever",
    "Segundos",
    "Minutos",
    "Horas",
    "Dias",
],

"zh": [
    "预测您达到社交媒体粉丝目标所需的时间",
    "初始粉丝",
    "当前粉丝",
    "期望的粉丝",
    "时间",
    "哎呀！您忘记填写一个或多个字段。",
    "您不能使用小于或等于0的数字。",
    "初始粉丝不能等于或少于当前粉丝。",
    "期望的粉丝不能少于或等于初始粉丝或当前粉丝。",
    "您将在以下时间达到您的目标：",
    "预测",
    "秒",
    "分钟",
    "小时",
    "天"
],

"ja": [
    "ソーシャルメディアのフォロワー目標達成までの時間を予測します",
    "初期フォロワー",
    "現在のフォロワー",
    "目標のフォロワー",
    "時間",
    "おっと！1つ以上のフィールドを記入するのを忘れてしまいました。",
    "0以下の数値は使用できません。",
    "初期フォロワーは現在のフォロワーより少なくても同じ数であってはなりません。",
    "目標のフォロワーは、初期のフォロワーまたは現在のフォロワーより少なくても同じ数であってはなりません。",
    "目標を達成するまでの時間：",
    "予測",
    "秒",
    "分",
    "時間",
    "日",
],

"ko": [
    "소셜 미디어 팔로워 목표 달성에 걸리는 예상 시간을 예측합니다",
    "초기 팔로워",
    "현재 팔로워",
    "원하는 팔로워",
    "시간",
    "이런! 하나 이상의 필드를 작성하지 않았습니다.",
    "0 이하의 숫자를 사용할 수 없습니다.",
    "초기 팔로워는 현재 팔로워와 동일하거나 그보다 적을 수 없습니다.",
    "원하는 팔로워는 초기 팔로워 또는 현재 팔로워보다 작거나 같을 수 없습니다.",
    "목표를 달성하는 데 걸리는 시간:",
    "예측",
    "초",
    "분",
    "시간",
    "일",
],

"de": [
    "Schätzen Sie, wie lange es dauern wird, Ihr Ziel für soziale Medien zu erreichen",
    "Anfängliche Anhänger",
    "Aktuelle Anhänger",
    "Gewünschte Anhänger",
    "Zeit",
    "Hoppla! Sie haben ein oder mehrere Felder vergessen auszufüllen.",
    "Sie können keine Zahl kleiner oder gleich 0 verwenden.",
    "Die anfänglichen Anhänger können nicht gleich oder weniger als die aktuellen Anhänger sein.",
    "Die gewünschten Anhänger können nicht kleiner oder gleich den anfänglichen Anhängern oder den aktuellen Anhängern sein.",
    "Sie werden Ihr Ziel erreichen in:",
    "Schätzen",
    "Sekunden",
    "Minuten",
    "Stunden",
    "Tage",
],

"ru": [
    "Предскажите, сколько времени вам потребуется, чтобы достичь вашей цели по количеству подписчиков в социальных сетях",
    "Исходное количество подписчиков",
    "Текущее количество подписчиков",
    "Желаемое количество подписчиков",
    "Время",
    "Упс! Вы забыли заполнить одно или несколько полей.",
    "Вы не можете использовать число, меньшее или равное 0.",
    "Исходное количество подписчиков не может быть равным или меньшим текущему количеству подписчиков.",
    "Желаемое количество подписчиков не может быть меньше или равно исходному количеству подписчиков или текущему количеству подписчиков.",
    "Вы достигнете своей цели через:",
    "Предскажите",
    "Секунды",
    "Минуты",
    "Часы",
    "Дни",
],

"uk": [
    "Передбачте, скільки часу знадобиться вам, щоб досягти своєї мети щодо підписників у соціальних мережах",
    "Початкові підписники",
    "Поточні підписники",
    "Бажані підписники",
    "Час",
    "Упс! Ви забули заповнити одне або декілька полів.",
    "Ви не можете використовувати число менше або рівне 0.",
    "Початкові підписники не можуть бути рівні або менше за поточних підписників.",
    "Бажані підписники не можуть бути менше або рівні початковим підписникам або поточним підписникам.",
    "Ви досягнете своєї мети за:",
    "Передбачити",
    "Секунди",
    "Хвилини",
    "Години",
    "Дні",
],

"el": [
    "Προβλέψτε πόσο χρόνο θα χρειαστείτε για να φτάσετε τον στόχο σας στους ακόλουθους σας στα social media",
    "Αρχικοί ακόλουθοι",
    "Τρέχοντες ακόλουθοι",
    "Επιθυμητοί ακόλουθοι",
    "Χρόνος",
    "Ουπς! Ξεχάσατε να συμπληρώσετε έναν ή περισσότερους τομείς.",
    "Δεν μπορείτε να χρησιμοποιήσετε έναν αριθμό μικρότερο ή ίσο με το 0.",
    "Οι αρχικοί ακόλουθοι δεν μπορούν να είναι ίσοι ή λιγότεροι από τους τρέχοντες ακόλουθους.",
    "Οι επιθυμητοί ακόλουθοι δεν μπορούν να είναι λιγότεροι ή ίσοι με τους αρχικούς ακόλουθους ή τους τρέχοντες ακόλουθους.",
    "Θα φτάσετε τον στόχο σας σε:",
    "Προβλέψτε",
    "Δευτερόλεπτα",
    "Λεπτά",
    "Ώρες",
    "Ημέρες",
],

"th": [
    "คาดการณ์เวลาที่จะใช้ในการเติบโตไปสู่จำนวนผู้ติดตามสังคมของคุณ",
    "จำนวนผู้ติดตามเริ่มต้น",
    "จำนวนผู้ติดตามปัจจุบัน",
    "จำนวนผู้ติดตามที่ต้องการ",
    "เวลา",
    "อุ๊ปส์! คุณลืมกรอกช่องที่หนึ่งหรือมากกว่า",
    "คุณไม่สามารถใช้ตัวเลขน้อยกว่าหรือเท่ากับ 0 ได้",
    "จำนวนผู้ติดตามเริ่มต้นไม่สามารถเท่ากับหรือน้อยกว่าจำนวนผู้ติดตามปัจจุบันได้",
    "จำนวนผู้ติดตามที่ต้องการไม่สามารถน้อยกว่าหรือเท่ากับจำนวนผู้ติดตามเริ่มต้นหรือจำนวนผู้ติดตามปัจจุบันได้",
    "คุณจะบรรลุเป้าหมายของคุณใน:",
    "คาดการณ์",
    "วินาที",
    "นาที",
    "ชั่วโมง",
    "วัน",
],

"da": [
    "Forudsig, hvor lang tid det vil tage dig at nå dit mål for antal følgere på sociale medier",
    "Start følgere",
    "Nuværende følgere",
    "Ønskede følgere",
    "Tid",
    "Ups! Du glemte at udfylde et eller flere felter.",
    "Du kan ikke bruge et tal mindre end eller lig med 0.",
    "Start følgerne kan ikke være lig med eller færre end de nuværende følgere.",
    "De ønskede følgere kan ikke være mindre end eller lig med de startende følgere eller de nuværende følgere.",
    "Du vil nå dit mål om:",
    "Forudsig",
    "Sekunder",
    "Minutter",
    "Timer",
    "Dage",
],

"sv": [
    "Förutsäg hur lång tid det kommer att ta dig att nå ditt mål för antal följare på sociala medier",
    "Inledande följare",
    "Aktuella följare",
    "Önskade följare",
    "Tid",
    "Hoppsan! Du glömde fylla i ett eller flera fält.",
    "Du kan inte använda ett nummer mindre än eller lika med 0.",
    "Inledande följare kan inte vara lika med eller färre än de aktuella följarna.",
    "De önskade följarna kan inte vara mindre än eller lika med de inledande följarna eller de aktuella följarna.",
    "Du kommer att nå ditt mål om:",
    "Förutsäg",
    "Sekunder",
    "Minuter",
    "Timmar",
    "Dagar",
],

"no": [
    "Forutsi hvor lang tid det vil ta deg å nå målet ditt for antall følgere i sosiale medier",
    "Initielle følgere",
    "Nåværende følgere",
    "Ønskede følgere",
    "Tid",
    "Oops! Du glemte å fylle inn ett eller flere felt.",
    "Du kan ikke bruke et tall mindre enn eller lik 0.",
    "De initielle følgerne kan ikke være lik eller færre enn de nåværende følgerne.",
    "De ønskede følgerne kan ikke være mindre enn eller lik de initielle følgerne eller de nåværende følgerne.",
    "Du vil nå målet ditt på:",
    "Forutsi",
    "Sekunder",
    "Minutter",
    "Timer",
    "Dager"
],

"fi": [
    "Ennusta, kuinka kauan kestää saavuttaa tavoitteesi sosiaalisen median seuraajamäärässä",
    "Alkuseuraajat",
    "Nykyiset seuraajat",
    "Toivotut seuraajat",
    "Aika",
    "Hupsista! Unohdit täyttää yhden tai useamman kentän.",
    "Et voi käyttää lukua, joka on pienempi tai yhtä suuri kuin 0.",
    "Alkuseuraajat eivät voi olla yhtä suuria tai vähemmän kuin nykyiset seuraajat.",
    "Toivotut seuraajat eivät voi olla vähemmän kuin tai yhtä suuria kuin alkuseuraajat tai nykyiset seuraajat.",
    "Saavutat tavoitteesi:",
    "Ennusta",
    "Sekunnit",
    "Minuutit",
    "Tunnit",
    "Päivät"
],

"ca": [
    "Preveu quant temps trigaràs a assolir l'objectiu de seguidors a les xarxes socials",
    "Seguidors inicials",
    "Seguidors actuals",
    "Seguidors desitjats",
    "Temps",
    "Oops! Has oblidat omplir un o més camps.",
    "No pots utilitzar un número menor o igual a 0.",
    "Els seguidors inicials no poden ser iguals o menors als seguidors actuals.",
    "Els seguidors desitjats no poden ser menors o iguals als seguidors inicials o als seguidors actuals.",
    "Assoliràs la teva meta en:",
    "Preveure",
    "Segons",
    "Minuts",
    "Hores",
    "Dies"
],

"vi": [
    "Dự đoán mất bao lâu để đạt được mục tiêu số lượng người theo dõi trên mạng xã hội của bạn",
    "Người theo dõi ban đầu",
    "Số người theo dõi hiện tại",
    "Số người theo dõi mong muốn",
    "Thời gian",
    "Oops! Bạn đã quên điền vào một hoặc nhiều trường.",
    "Bạn không thể sử dụng một số nhỏ hơn hoặc bằng 0.",
    "Số người theo dõi ban đầu không thể bằng hoặc ít hơn số người theo dõi hiện tại.",
    "Số người theo dõi mong muốn không thể ít hơn hoặc bằng số người theo dõi ban đầu hoặc số người theo dõi hiện tại.",
    "Bạn sẽ đạt được mục tiêu của mình trong:",
    "Dự đoán",
    "Giây",
    "Phút",
    "Giờ",
    "Ngày"
],

"pl": [
    "Przewidź, jak długo zajmie Ci osiągnięcie celu w liczbie obserwujących w mediach społecznościowych",
    "Początkowi obserwujący",
    "Aktualni obserwujący",
    "Pożądani obserwujący",
    "Czas",
    "Ups! Zapomniałeś wypełnić jedno lub więcej pól.",
    "Nie możesz używać liczby mniejszej lub równej 0.",
    "Początkowi obserwujący nie mogą być równe lub mniejsze od aktualnych obserwujących.",
    "Pożądani obserwujący nie mogą być mniejsi lub równe początkowym obserwującym lub aktualnym obserwującym.",
    "Osiągniesz swój cel za pomocą:",
    "Przewidź",
    "Sekundy",
    "Minuty",
    "Godziny",
    "Dni",
],

"hi": [
    "अपने सोशल मीडिया फॉलोअर्स लक्ष्य तक पहुंचने में आपको कितना समय लगेगा",
    "प्रारंभिक फॉलोअर्स",
    "वर्तमान फॉलोअर्स",
    "वांछित फॉलोअर्स",
    "समय",
    "ऊप्स! आपने एक या एक से अधिक फ़ील्ड भरना भूल गए हैं।",
    "आप 0 या उससे कम नंबर का उपयोग नहीं कर सकते।",
    "प्रारंभिक फॉलोअर्स वर्तमान फॉलोअर्स के समान या उससे कम नहीं हो सकते।",
    "वांछित फॉलोअर्स आरंभिक फॉलोअर्स या वर्तमान फॉलोअर्स से कम या बराबर नहीं हो सकते।",
    "आप अपनी लक्ष्य को प्राप्त करेंगे:",
    "पूर्वानुमान लगाएं",
    "सेकंड्स",
    "मिनट्स",
    "घंटे",
    "दिन",
],

"is": [
    "Spáðu því hversu langt mun taka þig að ná markmiðum þínum um fjölda fylgjenda á samfélagsmiðlum",
    "Upphaflegir fylgjendur",
    "Núverandi fylgjendur",
    "Óskaðir fylgjendur",
    "Tími",
    "Upps! Þú gleymdir að fylla út í eitt eða fleiri reiti.",
    "Þú getur ekki notað tölu sem er minni eða jafnt og 0.",
    "Upphaflegu fylgjendurnir geta ekki verið jafnir eða færri en núverandi fylgjendur.",
    "Óskaðir fylgjendur geta ekki verið minni eða jafnir og upphaflegir fylgjendur eða núverandi fylgjendur.",
    "Þú munt ná markmiðum þínum á:",
    "Spá",
    "Sekúndur",
    "Mínútur",
    "Klukkustundir",
    "Dagar",
],



}

function translate(lan){
    p_html = document.querySelectorAll("p")
    p_html[0].innerText = languages[lan][0]
    
    input_html = document.querySelectorAll("input")
    input_html[0].placeholder = languages[lan][1]
    input_html[1].placeholder = languages[lan][2]
    input_html[2].placeholder = languages[lan][3]
    input_html[3].placeholder = languages[lan][4]
    
    option_html = document.querySelectorAll("option")
    option_html[0].innerText = languages[lan][11]
    option_html[1].innerText = languages[lan][12]
    option_html[2].innerText = languages[lan][13]
    option_html[3].innerText = languages[lan][14]
    
    document.querySelector("button").innerHTML = `<i class="bi bi-stars"></i>${languages[lan][10]}`
    
    document.querySelector("h2").innerText = languages[lan][9]
    
    span_html = document.querySelectorAll("span")
    span_html[1].innerText = languages[lan][11]
    span_html[3].innerText = languages[lan][12]
    span_html[5].innerText = languages[lan][13]
    span_html[7].innerText = languages[lan][14]
}

//console.log(languages[navigator.language][0])
